name: Golang CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  golang:
    name: "Golang"
    runs-on: ubuntu-latest
    env:
      GO111MODULE: "on"

    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: "~1.16.3"

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
          
      - run: go env
      - run: go version
  
  version:
    name: "Version" 
    runs-on: ubuntu-latest
    steps:
      - run: go env
      - run: go version
    
